### ISSUE TITLE
Error: getting an id not defined in api-helpers when creating a case

### ISSUE THREAD

**Issue by denisinla** [truevault/truevault-react-js-sample-app#5]
Looks like there may be some breaking changes in the updated dependencies for this sample project. 
I'm unable to create a new case with console returning an error found in api-helpers.js. Looks like caseDocId is not being defined. 

I rolled back the package.json changes made and it started working again. Perhaps a breaking change in redux-promise?

**Comment by runt9** [comment]
Hello, I'm having trouble reproducing your issue with the information given. Can you let me know what version of Node you're on as well as the full error output you're experiencing? This will help me further diagnose the issue.
